import path from "node:path";
import { getFilePattern } from "../rules/resolver.js";
import type {
	FilesConfig,
	ImportRule,
	ImportsConfig,
	RulesByDirectory,
	ZoneFenceConfig,
} from "../rules/types.js";

export const DOCS_LANGUAGES = ["en", "ja"] as const;

export type DocsLanguage = (typeof DOCS_LANGUAGES)[number];

export function isDocsLanguage(value: string): value is DocsLanguage {
	return (DOCS_LANGUAGES as readonly string[]).includes(value);
}

export interface DocsOptions {
	/** Directory that paths in the document are relative to. Defaults to the working directory. */
	cwd?: string;
	lang?: DocsLanguage;
}

interface Labels {
	title: string;
	generated: string;
	directory: string;
	designIntent: string;
	allowed: string;
	denied: string;
	files: string;
	typeOnly: string;
	valueOnly: string;
	onlyFiles: (patterns: string) => string;
	requiredSibling: (target: string, sibling: string) => string;
	reason: (text: string) => string;
	empty: string;
}

const LABELS: Record<DocsLanguage, Labels> = {
	en: {
		title: "Architecture Rules",
		generated: "Generated by `zonefence docs` from zonefence.yaml. Do not edit by hand.",
		directory: "Directory",
		designIntent: "Design intent",
		allowed: "Allowed",
		denied: "Denied (reason)",
		files: "Files",
		typeOnly: "type only",
		valueOnly: "value only",
		onlyFiles: (patterns) => `Only ${patterns}`,
		requiredSibling: (target, sibling) => `${target} requires ${sibling}`,
		reason: (text) => ` (${text})`,
		empty: "-",
	},
	ja: {
		title: "アーキテクチャルール",
		generated: "`zonefence docs` が zonefence.yaml から生成しました。直接編集しないでください。",
		directory: "ディレクトリ",
		designIntent: "設計意図",
		allowed: "許可",
		denied: "禁止（理由）",
		files: "ファイル",
		typeOnly: "型のみ",
		valueOnly: "値のみ",
		onlyFiles: (patterns) => `${patterns} のみ`,
		requiredSibling: (target, sibling) => `${target} には ${sibling} が必要`,
		reason: (text) => `（${text}）`,
		empty: "-",
	},
};

interface DocsRow {
	directory: string;
	description?: string;
	imports?: ImportsConfig;
	files?: FilesConfig;
}

/**
 * Generate a Markdown document from the rule files, so that the written
 * architecture guide cannot drift from what is actually enforced.
 *
 * One row per directory that has a zonefence.yaml, and one per `directoryPatterns`
 * entry. Rules are shown as written, without inheritance applied.
 */
export function generateDocs(rules: RulesByDirectory, options: DocsOptions = {}): string {
	const cwd = options.cwd ?? process.cwd();
	const labels = LABELS[options.lang ?? "en"];
	const rows = collectRows(rules, cwd);
	const withFiles = rows.some((row) => hasFileRules(row.files));

	const header = [
		labels.directory,
		labels.designIntent,
		labels.allowed,
		labels.denied,
		...(withFiles ? [labels.files] : []),
	];

	const lines = [
		`# ${labels.title}`,
		"",
		`<!-- ${labels.generated} -->`,
		"",
		formatRow(header),
		formatRow(header.map(() => "---")),
		...rows.map((row) =>
			formatRow([
				code(row.directory),
				row.description ? escapeCell(row.description) : labels.empty,
				formatImportRules(row.imports?.allow, labels),
				formatImportRules(row.imports?.deny, labels),
				...(withFiles ? [formatFileRules(row.files, labels)] : []),
			]),
		),
	];

	return `${lines.join("\n")}\n`;
}

function collectRows(rules: RulesByDirectory, cwd: string): DocsRow[] {
	const rows: DocsRow[] = [];

	for (const directory of Object.keys(rules).sort()) {
		const { config } = rules[directory];
		const relativeDirectory = path.relative(cwd, directory) || ".";

		if (hasOwnRules(config)) {
			rows.push({
				directory: relativeDirectory,
				description: config.description,
				imports: config.imports,
				files: config.files,
			});
		}

		for (const patternRule of config.directoryPatterns ?? []) {
			rows.push({
				directory: path.posix.join(relativeDirectory, patternRule.pattern),
				description: patternRule.config.description,
				imports: patternRule.config.imports,
				files: patternRule.config.files,
			});
		}
	}

	return rows;
}

/** A file that only carries `directoryPatterns` has nothing of its own to document. */
function hasOwnRules(config: ZoneFenceConfig): boolean {
	return (
		config.description !== undefined ||
		(config.imports?.allow?.length ?? 0) > 0 ||
		(config.imports?.deny?.length ?? 0) > 0 ||
		hasFileRules(config.files)
	);
}

function hasFileRules(files: FilesConfig | undefined): boolean {
	return (files?.allow?.length ?? 0) > 0 || (files?.require?.length ?? 0) > 0;
}

function formatImportRules(rules: ImportRule[] | undefined, labels: Labels): string {
	if (!rules || rules.length === 0) {
		return labels.empty;
	}

	return rules
		.map((rule) => {
			const kind =
				rule.kind === "type"
					? ` _${labels.typeOnly}_`
					: rule.kind === "value"
						? ` _${labels.valueOnly}_`
						: "";
			const reason = rule.message ? labels.reason(escapeCell(rule.message)) : "";
			return `${code(rule.from)}${kind}${reason}`;
		})
		.join(", ");
}

function formatFileRules(files: FilesConfig | undefined, labels: Labels): string {
	const parts: string[] = [];

	if (files?.allow && files.allow.length > 0) {
		parts.push(labels.onlyFiles(files.allow.map((rule) => code(getFilePattern(rule))).join(", ")));
	}

	for (const requirement of files?.require ?? []) {
		const reason = requirement.message ? labels.reason(escapeCell(requirement.message)) : "";
		parts.push(
			`${labels.requiredSibling(code(requirement.for), code(requirement.sibling))}${reason}`,
		);
	}

	return parts.length > 0 ? parts.join("<br>") : labels.empty;
}

function formatRow(cells: string[]): string {
	return `| ${cells.join(" | ")} |`;
}

/** Inline code. A pipe would end the table cell even inside backticks. */
function code(value: string): string {
	return `\`${value.replace(/\|/g, "\\|")}\``;
}

function escapeCell(value: string): string {
	return value.trim().replace(/\|/g, "\\|").replace(/\r?\n/g, "<br>");
}
