import path from "node:path";
import { describe, expect, it } from "vitest";
import { loadRulesForDirectory } from "../rules/loader.js";
import type { RulesByDirectory } from "../rules/types.js";
import { generateDocs, isDocsLanguage } from "./markdown.js";

const CWD = "/project";

function tableRows(markdown: string): string[] {
	return markdown.split("\n").filter((line) => line.startsWith("| `"));
}

// See https://github.com/Glider2355/zonefence/issues/18
describe("generateDocs", () => {
	const rules: RulesByDirectory = {
		"/project/src/packages/novel/core": {
			config: {
				version: 1,
				description: "Core layer - pure business logic",
				imports: {
					allow: [{ from: "@/packages/novel/core/**" }, { from: "neverthrow" }],
					deny: [{ from: "hono", message: "Core cannot depend on an HTTP framework" }],
				},
			},
			ruleFilePath: "/project/src/packages/novel/core/zonefence.yaml",
		},
	};

	it("should render one row per rule file with intent, allow and deny", () => {
		const markdown = generateDocs(rules, { cwd: CWD });

		expect(markdown).toBe(
			[
				"# Architecture Rules",
				"",
				"<!-- Generated by `zonefence docs` from zonefence.yaml. Do not edit by hand. -->",
				"",
				"| Directory | Design intent | Allowed | Denied (reason) |",
				"| --- | --- | --- | --- |",
				"| `src/packages/novel/core` | Core layer - pure business logic | `@/packages/novel/core/**`, `neverthrow` | `hono` (Core cannot depend on an HTTP framework) |",
				"",
			].join("\n"),
		);
	});

	it("should render Japanese headings with --lang ja", () => {
		const markdown = generateDocs(rules, { cwd: CWD, lang: "ja" });

		expect(markdown).toContain("| ディレクトリ | 設計意図 | 許可 | 禁止（理由） |");
		expect(markdown).toContain("`hono`（Core cannot depend on an HTTP framework）");
	});

	it("should render one row per directoryPatterns entry", () => {
		const markdown = generateDocs(
			{
				"/project/src/pages": {
					config: {
						version: 1,
						directoryPatterns: [
							{
								pattern: "**/containers",
								config: {
									description: "Container layer",
									imports: { allow: [{ from: "../presenters/**" }] },
								},
							},
							{ pattern: "**/presenters", config: { imports: { deny: [{ from: "axios" }] } } },
						],
					},
					ruleFilePath: "/project/src/pages/zonefence.yaml",
				},
			},
			{ cwd: CWD },
		);

		// The file itself has no rules of its own, so only the patterns are listed
		expect(tableRows(markdown)).toEqual([
			"| `src/pages/**/containers` | Container layer | `../presenters/**` | - |",
			"| `src/pages/**/presenters` | - | - | `axios` |",
		]);
	});

	it("should sort directories and keep patterns next to the file that defines them", () => {
		const markdown = generateDocs(
			{
				"/project/src/b": {
					config: { version: 1, description: "B" },
					ruleFilePath: "/project/src/b/zonefence.yaml",
				},
				"/project/src/a": {
					config: {
						version: 1,
						description: "A",
						directoryPatterns: [{ pattern: "*/x", config: { description: "X" } }],
					},
					ruleFilePath: "/project/src/a/zonefence.yaml",
				},
			},
			{ cwd: CWD },
		);

		expect(tableRows(markdown).map((row) => row.split(" | ")[0])).toEqual([
			"| `src/a`",
			"| `src/a/*/x`",
			"| `src/b`",
		]);
	});

	it("should mark type-only and value-only rules", () => {
		const markdown = generateDocs(
			{
				"/project/src/use-case": {
					config: {
						version: 1,
						imports: {
							allow: [{ from: "../gateway/**", kind: "type" }],
							deny: [{ from: "../gateway/**", kind: "value", message: "No implementations" }],
						},
					},
					ruleFilePath: "/project/src/use-case/zonefence.yaml",
				},
			},
			{ cwd: CWD },
		);

		expect(tableRows(markdown)).toEqual([
			"| `src/use-case` | - | `../gateway/**` _type only_ | `../gateway/**` _value only_ (No implementations) |",
		]);
	});

	it("should add a Files column only when some rule constrains files", () => {
		expect(generateDocs(rules, { cwd: CWD })).not.toContain("Files");

		const markdown = generateDocs(
			{
				"/project/src/api/routes": {
					config: {
						version: 1,
						files: {
							allow: ["route.ts", "*Dto.ts"],
							require: [{ for: "*.test.ts", sibling: "{stem}.ts", message: "Colocate tests" }],
						},
					},
					ruleFilePath: "/project/src/api/routes/zonefence.yaml",
				},
			},
			{ cwd: CWD },
		);

		expect(markdown).toContain("| Directory | Design intent | Allowed | Denied (reason) | Files |");
		expect(tableRows(markdown)).toEqual([
			"| `src/api/routes` | - | - | - | Only `route.ts`, `*Dto.ts`<br>`*.test.ts` requires `{stem}.ts` (Colocate tests) |",
		]);
	});

	it("should escape pipes and newlines so that a cell cannot break the table", () => {
		const markdown = generateDocs(
			{
				"/project/src/core": {
					config: {
						version: 1,
						description: "Pure | no IO\nsecond line",
						imports: { deny: [{ from: "{a,b}|c", message: "x | y" }] },
					},
					ruleFilePath: "/project/src/core/zonefence.yaml",
				},
			},
			{ cwd: CWD },
		);

		expect(tableRows(markdown)).toEqual([
			"| `src/core` | Pure \\| no IO<br>second line | - | `{a,b}\\|c` (x \\| y) |",
		]);
	});

	it("should name the working directory itself as `.`", () => {
		const markdown = generateDocs(
			{
				"/project": {
					config: { version: 1, description: "Root" },
					ruleFilePath: "/project/zonefence.yaml",
				},
			},
			{ cwd: CWD },
		);

		expect(tableRows(markdown)).toEqual(["| `.` | Root | - | - |"]);
	});

	it("should document the colocation fixture", async () => {
		const fixtureRoot = path.resolve(__dirname, "../../test-fixtures/colocation");
		const loaded = await loadRulesForDirectory(path.join(fixtureRoot, "src"));

		const rows = tableRows(generateDocs(loaded, { cwd: fixtureRoot }));

		expect(rows.map((row) => row.split(" | ")[0])).toEqual([
			"| `src/pages`",
			"| `src/pages/**/containers`",
			"| `src/pages/**/presenters`",
		]);
	});
});

describe("isDocsLanguage", () => {
	it("should recognize the supported languages", () => {
		expect(isDocsLanguage("en")).toBe(true);
		expect(isDocsLanguage("ja")).toBe(true);
		expect(isDocsLanguage("fr")).toBe(false);
	});
});
