version: 1

description: "Domain layer - pure business logic without external dependencies"

imports:
  allow:
    - from: "./**"
  deny:
    - from: "axios"
      message: "Domain layer should not depend on HTTP libraries"
    - from: "../infrastructure/**"
      message: "Domain layer cannot depend on Infrastructure layer"
